MACHINE = "hostbuild"
# Machine name

# Target Architecture
TARGET_ARCH = "powerpc64"
# Set the cross-compiler to use powerpc64le
TARGET_CC_ARCH += "-m64 -mcpu=power8 -mtune=power9"
TARGET_CXX_ARCH +="-m64 -mcpu=power8 -mtune=power9"

GCCVERSION = "8.2%"
DEFAULTTUNE = "powerpc64"
TUNE_FEATURES = "powerpc64"

# Add support for necessary packages
# MACHINE_FEATURES += "efi"

# Ensure package architectures match
PACKAGE_EXTRA_ARCHS = "powerpc64"
TARGET_CC_ARCH = "-m64 -mbig-endian -mcpu=power8 -mtune=power9"

# Select a valid PowerPC64LE-compatible machine as a base
require conf/machine/include/powerpc/arch-powerpc64.inc
